### PR TITLE
feat: support multiple discord roleIds as staff

### PR DESCRIPTION
**Pull request by solareon**
By storing roleIDs as a table and then checking if a roleId is present in the table we can support multiple roleIds to authenticate as staff.

### CODE REVIEW

**Comment by vipexv** [comment]
Sorry for the late reply, I'll look into this when I'm back on, thank you!

**Review by vipexv — APPROVED** [review]
LGTM.

**Comment by solareon** [comment]
> Sorry for the late reply, I'll look into this when I'm back on, thank you!

No rush. Glad I was able to contribute

**Comment by vipexv** [comment]
Thank you once again, hope you have a good day!

**Pull request merged**
